### ISSUE TITLE
About the use of software

### ISSUE THREAD

**Issue by dabaicai521** [Apollo3zehn/ImcFamosFile#7]
Hello, can you provide a complete free IMC Famos software?  I also use it to draw wind turbine power curves.  thank you

**Comment by Apollo3zehn** [comment]
What do you mean? This library is only for reading and writing Famos files (for free of course). It is not a replacement for Famos but may help to become independent of it by converting the data into other common formats.

**Comment by dabaicai521** [comment]
I see. Thank you.
