### ISSUE TITLE
Issue with compile the project with VS2013

### ISSUE THREAD

**Issue by Flow75** [Apollo3zehn/ImcFamosFile#8]
Hello, 

I would like to compile your project with VS2013 or get it from Nugget Package manager.

- When I compile, I have an error "There is no target in the project"

- When I want to download the package from Nugget, I have this error what ever the .NET version I set (4.5, 4.5,1, 4.8)
![Uploading image.png…]()

Could you help me :)

Thx.
F.

**Comment by Apollo3zehn** [comment]
This library targets .NET Standard 2.1 which means you need to use at least .NET Core 3.0 (https://docs.microsoft.com/de-de/dotnet/standard/net-standard?tabs=net-standard-2-1).

However, you can change it use netstandard2.0 instead (maybe even lower) here: https://github.com/Apollo3zehn/ImcFamosFile/blob/c77170037bf6b0cc753f954b04c42dc9d02ebc0b/src/ImcFamosFile/ImcFamosFile.csproj#L7

You would then need to fix some minor compilation errors:

![image](https://user-images.githubusercontent.com/20972129/169060913-c40446bf-b04b-47e1-a21d-7e52e0bb0ad2.png)

Maybe you also need to explicitly reference the System.Memory package for a backport of the new `Span` support.

**Comment by Apollo3zehn** [comment]
However, I am not sure it will work with VS 2013 (does it support the new .csproj format)?
